# Generated by Django 3.0.3 on 2020-04-29 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdiet', '0002_auto_20200429_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal_details',
            options={'verbose_name_plural': 'Patients details'},
        ),
        migrations.CreateModel(
            name='Health_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previously_diagnised_disease', models.CharField(max_length=30)),
                ('currently_diagonised_disease', models.CharField(max_length=30)),
                ('year_diagonised', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('muac', models.IntegerField()),
                ('on_arvs', models.BooleanField()),
                ('cd4_count', models.IntegerField()),
                ('tca', models.IntegerField()),
                ('clinician_designation', models.CharField(max_length=50)),
                ('patient_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientdiet.Personal_details')),
            ],
            options={
                'verbose_name_plural': 'Health Details',
            },
        ),
    ]
