# Generated by Django 3.0.2 on 2020-05-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdiet', '0006_auto_20200504_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_details',
            name='name',
        ),
        migrations.AddField(
            model_name='health_details',
            name='names',
            field=models.ForeignKey(default='mutahi kagwe', on_delete=django.db.models.deletion.CASCADE, to='patientdiet.Personal_details'),
        ),
    ]
